#!/bin/bash

###Skript küsib kasutajalt ridade arvu ja väljastab vastavalt ###
###sellele püramiidi kujundi antud ridade arvuga.             ###  

echo -n "Sisesta ridade arv:"
read arv

for (( i=1; i<=$arv; i++ )); do 
echo -n "$i."

  for(( j=1; j<=i; j++ )); do
    echo -n "* "
 
 done
  echo 
done






