#!/bin/bash

#Skript mis küsib kasutajalt ühe arvu ja väljastab antud arvu numbrite summa

echo "Sisesta suvaline täisarv:"
read arv
summa=0
while [ $arv -ne 0 ];
do 
	jaak=$(($arv % 10))
	summa=$(($summa + $jaak))
	arv=$(($arv / 10))
done
echo "Arvu numbrite summa on $summa"
