#!/bin/bash

###Skripti nimi: kujund ###
###Skripti looja: Tanel Märjama ###
###Skripti kirjeldus: küsib kasutajalt ridade arvu ja väljastab vastavalt ###
###sellele tagurpidi püramiidi kujundi antud ridade arvuga.               ###  

echo "Sisesta ridade arv:"

read arv

for((i=$arv; i>=1; i--))
do
  for((j=1; j<=i; j++))
  do
    echo -n "* "
  done
  echo
done






