#!/bin/bash

### Skripti nimi: menu ###
### Skripti looja: Tanel Märjama ###
### Skripti info: Skript annab käivitamisel kasutajale valiku kolme erineva ###
### toidu vahel, palub kasutajal valida ühe ja seejärel väljastab valiku    ###
### kohta kommentaari.                                                      ###


echo "1) liha ja kartulid"
echo "2) kala ja krõpsud"
echo "3) supp ja salat"

echo "Tee oma valik (1 või 2 või 3):"
read arv

if [ $arv = 1 ] ; then
	echo "Väga maitsev, aga jälgi oma tervist!"
	echo "Head isu!"
elif [ $arv = 2 ] ; then
	echo "Brititoit on maitsev!"
	echo "Head isu!"
elif [ $arv = 3 ] ; then
	echo "Nii tervislik ja igav..."
	echo "Head isu!"
else	
	echo "Vali õige number"
fi


